config/routes.rb
Umweltpaedagogik::Application.routes.draw do

  get "/offers", to: "static_pages#offers"
  get "/photos", to: "static_pages#photos"
  get "/videos", to: "static_pages#videos"
  get "/aboutUs",to: "static_pages#aboutUs"
  get "/kunden",to: "static_pages#kunden"
  get "/medienberichte",to: "static_pages#medienberichte"
  

  root 'static_pages#home'

  resources "contacts", only: [:new, :create]

  

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :school_information
  attribute :name_teacher
	attribute :email, validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone
  attribute :class_information
  attribute :motivation

  attribute :course
  attribute :course_date
	attribute :nickname, captcha: true


  def headers
    {
      subject: "Neue Anmeldung für '#{course}'",
      to: "barbara.schumacher@bluewin.ch", # barbara.schumacher@bluewin.ch
      from: %("#{name_teacher}" <#{email}>)
    }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
# coding: utf-8
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
		@contact.course = []
		@contact.course << "Kompostieren, die Tierwelt im Kompost / 2 Lektionen"
		@contact.course << "Recycling und Kompostieren / 2 Lektionen"
		@contact.course << "Kompostmobil / 2‒4 Lektionen"
		@contact.course << "Umwelttheater Figurenspiel 1: Kompostieren + Littering / 2 Lektionen"
        @contact.course << "Figurenspiel Madame Poubelle, Recycling + vermeiden / 2 Lektionen"
		@contact.course << "Schulgarten-Projekt"
		@contact.course << "Recycling, Kompostieren + erneuerbare Energie durch Biomassenvergärung / 3,5 Std."
		@contact.course << "Littering in der Gemeinde + Naturkreisläufe im Wald / 3,5 Std."
		@contact.course << "Abfallvermeidung in der Kehrichtverbrennung Basel / 3 Std."
        @contact.course << "Abfall im Schulalltag"
		@contact.course << "Tipps und Hintergründe zum täglichen Abfallvermeiden / 2 Lektionen."
        @contact.course << "Elektroschrott vermeiden und Recycling 2 Lektionen"
		@contact.course << "Abfallvermeidung, Recycling und Basteln mit Abfall / 2 Lektionen"
		@contact.course << "Littering, Recycling auf Werkhof / 3 Std."
		@contact.course << "Littering ums Schulhaus und in der Gemeinde / 2 Lektionen"
		@contact.course << "Anti-Littering-Einsatz in der Gemeinde / 4 Std."
		@contact.course << "Anti-Littering Wanderung / 4 Std."
		@contact.course << "Figurenspiel 3: Das sprechende Sandwitch / 2 Lektionen"
		@contact.course << "Foodwaste / 2 Lektionen"
		@contact.course << "Abfall im Wasser / 2‒4 Lektionen."
		@contact.course << "Bachputzede / 4 Std."
		@contact.course << "Ein Morgen rund um das Thema Wasser"
		@contact.course << "Energieeffizienz Einführungskurs / 2 Lektionen"
		@contact.course << "Umwelteinsätze in der Gemeinde / 4-6 Std."
        @contact.course << "Projekttag oder Projektwochen"
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request =request

		if @contact.deliver
			flash[:notice] = "Vielen Dank für die Anmeldung"
			redirect_to offers_path
		else
			flash.now[:error] = "Leider können zur Zeit keine Anmeldungen vorgenommen werden."
			render new
		end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def offers
  end

  def aboutUs
  end

  def photos
    @littering_im_waldkurs = Dir.glob("app/assets/images/gallery/littering_im_waldkurs/*tb*")
    @kompostkurs_kindergarten = Dir.glob("app/assets/images/gallery/kompostkurs_kindergarten/*tb*")
    @werken_mit_abfall = Dir.glob("app/assets/images/gallery/werken_mit_abfall/*tb*")
    @anti_littering = Dir.glob("app/assets/images/gallery/anti_littering/*tb*")
    @sek = Dir.glob("app/assets/images/gallery/anti_littering/sek/*tb*")
    @sek_bi = Dir.glob("app/assets/images/gallery/anti_littering/sek_bi/*tb*")
    @jug_therwil = Dir.glob("app/assets/images/gallery/anti_littering/jug_therwil/*tb*")  
    @abfallwettspiele = Dir.glob("app/assets/images/gallery/abfallwettspiele/*tb*")
    @kompostmobil = Dir.glob("app/assets/images/gallery/kompostmobil/*tb*")
    @prim_kind_aesch = Dir.glob("app/assets/images/gallery/kompostmobil/prim_kind_aesch/*tb*")
    @mme_poubelle = Dir.glob("app/assets/images/gallery/mme_poubelle/*tb*")

    
  end

  def videos
  end

  def kunden
  end
  
  def kurs_effizienz
  end

  def medienberichte
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

	def get_original(image, category)
		get_image_path(image, category).gsub!(/_([a-z]+).jpg/, '_og.jpg')
	end

	def get_image_path(image, category)
		"gallery/#{category}/#{image.split('/').last}"
	end
end

app/views/contacts/create.html.haml
%article#main
  %h1 Vielen Dank für Ihre Anmeldung.

app/views/contacts/new.html.haml
%article#main
  %h3 Umwelt- und Abfallpädagogik Anmeldeformular 
  = simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f|
    = f.input :school_information, required: true, label: "Schulhaus, Adresse und Telefonnummer Schule", :as => :text, :input_html => {:rows => 2}
    = f.input :name_teacher, required: true, label: "Name Lehrperson"
    = f.input :email, required: true, label: "E-Mail-Adresse"
    = f.input :phone, required: true, label: "Natel- und Telefonnummer"
    = f.input :class_information, :required => true, label: "Klasse und Anzahl Schüler/innen"
    = f.input :motivation, :required => true, label: "Motivation und Disziplin Schüler/innen", :as => :text, :input_html => {:rows => 2}
    %br/
    %h1 Kurse
    = f.input :course, collection: @contact.course, label: "Kurs"
    = f.input :course_date, :as => :text, :input_html => {:rows => 2}, label: "Wunschdaten (mind. 3 Vorschläge) bzw. mögliche Wochentage und Monate"
    
    .hidden
      = f.input :nickname, :hint => 'Whats your nickname?'
    .form-actions
      = f.button :submit, 'Anmeldung Absenden', :class=> "btn btn-primary", id: "submit_contact"

app/views/layouts/_footer.html.haml
%footer#footer
	.clear
	#contact
		%h4 Kontakt
		%p
			Barbara Schumacher
			%br/
			Hauptstrasse 26
			%br/
			CH-4105 Biel-Benken
			%br/
			%a{href: "#"} barbara.schumacher@bluewin.ch
	#copyright
		Created by Nicolas Mauchle
		%br/
		&copy;Umweltpädagogik All rights reserved.
.clear

	

app/views/layouts/_header.html.haml
%section#banner
  .inner
    %header
      = link_to "Umweltpädagogik", root_path()

%section#header
  %nav#nav
    %ul
      %li= link_to "Home", root_path()
      %li= link_to "Angebot", offers_path()
      %li= link_to "Fotos", photos_path()
      %li= link_to "Filme", videos_path()
      %li= link_to "Über uns", aboutUs_path()
      %li= link_to "Kunden", kunden_path()
      %li= link_to "Medienberichte",  medienberichte_path()

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Umweltpaedagogik
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "true"
    = javascript_include_tag "application", "data-turbolinks-track": "true"
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/static_pages/_eltern.html.haml
%div
  / Kompostieren
  %h4 Elternkurse und Eltern-Kind-Kurse
  %p
    Einzelne Klassen oder ganze Schulhäuser können in Zusammenhang mit den Klassenkursen auch Elternkurse oder Eltern-Kind-Kurse besuchen. Damit möglichst viele Eltern an den Kursen teilnehmen können, finden diese meist an einem Samstagvormittag von 9.00 bis etwa 11.30 Uhr statt. Das Kursprogramm kann individuell zusammengestellt werden. Die Organisation und die Koordination sowie die Beschaffung des Budgets übernimmt Barbara Schumacher.
  %br/
  #orders
    .column.twelve.last
      %table
        %tr
          %td.middle.orderTitle
            %code.middle
              Projektleitung
          %td.middle
            %code.middle
              Barbara Schumacher in Zusammenarbeit mit Gemeinde und Schulleitung
        %tr
          %td.middle.orderTitle
            %code.middle
              Kursleitung
          %td.middle
            %code.middle
              Barbara Schumacher
        %tr
          %td.middle.orderTitle
            %code.middle
              Projektziel
          %td.middle
            %code.middle
              Die Schüler/innen und Eltern erhalten ein vertieftes Wissen über die diversen Abfall- und 
        %tr
          %td.middle.orderTitle
            %code.middle
              Stufen
          %td.middle
            %code.middle
              Primarschule ohne Kindergärten
  .clear
  %hr.hr/

app/views/static_pages/_lehrer_weiterbildung.html.haml
%div
  / Kompostieren
  %h4 Lehrerweiterbildung
  %p
    Die Lehrpersonen haben die Möglichkeit, z.B. vor der Durchführung diverser Abfall- und Umweltpädagogikkurse oder der Projektwoche, individuelle Weiterbildungskurse zu besuchen. Das Kursangebot wird auf Wunsch zusammengestellt.
  %br/
  #orders
    .column.twelve.last
      %table
        %tr
          %td.middle.orderTitle
            %code.middle
              Kursleitung
          %td.middle
            %code.middle
              Barbara Schumacher  und Birgit Gluth in Zusammenarbeit mit Schulleitung und Gemeinde
  .clear
  %hr.hr/

app/views/static_pages/aboutUs.html.haml
%article#main
  %h1 Wer wir sind
  .row.row-content.buffer
    .column.two#barbara
      %a{href: "#barbara"}
        = image_tag('aboutUs/Barbara_Schumacher_tb.jpg' )
      .foto_by
        Bild Hansjörg Walter
      %h6
        Barbara Schumacher
      %a{href: "#barbara"}
        .show_profile Profil anzeigen
      %br/
    
    .column.two#doris
      %a{href: "#doris"}
        = image_tag('aboutUs/Doris_Weiller_tb.jpg' )
      .foto_by
        Bild Umwelpädagogik.ch
      %h6
        Doris Weiller
      %a{href: "#doris"}
        .show_profile Profil anzeigen
      %br/
    
    .column.two#david
      %a{href: "#david"}
        = image_tag('aboutUs/David_Iten_tb.jpg' )
      .foto_by
        Bild Umwelpädagogik.ch
      %h6
        David Iten
      %a{href: "#david"}
        .show_profile Profil anzeigen
      %br/

    .column.two#sabine
      %a{href: "#sabine"}
        = image_tag('aboutUs/Sabine_Schaedler_tb.jpg' )
      .foto_by
        Bild Umwelpädagogik.ch
      %h6
        Sabine Schädler
      %a{href: "#sabine"}
        .show_profile Profil anzeigen
      %br/

    .column.two.last#michelle
      %a{href: "#michelle"}
        = image_tag('aboutUs/Michelle_Meier_tb.jpg' )
      .foto_by
        Bild Umwelpädagogik.ch
      %h6
        Michelle Meier
      %a{href: "#michelle"}
        .show_profile Profil anzeigen
      %br/
    
  .clear
  %br/
  #cv_barbara
    .column.two.reset
      %h5 Privat
    .column.ten.reset
      Geboren am 2. Juni 1964 in Basel
      %br/
      Mutter einer jugendlichen Tochter.
    .clear

    %hr.hr_us
    .column.two.reset
      %h5 Berufliches
    .column.ten.reset
      Seit 10 Jahren fast täglich als Umwelt- und Abfallpädagogin im Einsatz.
      %br/
      Tätig für folgende Firmen, Schulen und Organisationen
      %br/
      %br/
      .column.four.reset
        #title_institut Energie Zukunft Schweiz
      .column.eight.reset
        Guide auf Anlagen für erneuerbare Energie und   Marketingplanung für deren Schulprojekte
      .clear
      %br/
      .column.four.reset
        #title_institut Amt für Umweltschutz und Abfallpädagogin Energie Basel
      .column.eight.reset
        Abfallpädagogin
      .clear
      %br/
      .column.four.reset
        #title_institut Gemeinden
        Aesch, Allschwil, Biel-Benken, Binningen, Birsfelden, Bottmingen, Ettingen, Muttenz, Oberwil, Reinach, Therwil
      .column.eight.reset
        Abfall- und Umweltpädagogin und Beraterin Anti-Littering Kampagnen Abfallarme Veranstaltungen
      .clear
      %br/
      .column.four.reset
        #title_institut Natur- und Vogelschutzverein Oberwil
      .column.eight.reset
        Beraterin, Mitorganisation und Realisation von Projekten und Anlässen
      .clear
      %br/
      .column.four.reset
        #title_institut Umwelt und Landschaft Therwil
      .column.eight.reset
      .clear
      %br/
      .column.four.reset
        #title_institut Umweltschutzkommission Biel-Benken
      .column.eight.reset
        Präsidentin
      .clear
    .clear
    %hr.hr_us
    .column.two.reset
      %h5 Berufliche Entwicklung
    .column.ten.reset
      #timeline.container
        .timeline-block
          .timeline-content
            %h2 Projektleiterin Distributionskommunikation
            %p Schweizer Radio DRS, Basel und Zürich
            %span.date 2001 bis 2007
        .timeline-block
          .timeline-content
            %h2 Marketingberatung und -realisation
            %p Atelier 111 Ökobau, Basel
            %span.date 1999 bis 2000
        .timeline-block
          .timeline-content
            %h2 Produktmanagerin OTC-Heilmittel, Diätetika, Mutter&Kind
            %p Weleda AG, Arlesheim
            %span.date 1990 bis 1999
    .clear
    %hr.hr_us
    .column.two.reset
      %h5 Weitere Interessen
    .column.ten.reset
      Jogging, Yoga, Mountainbike, Wandern, Gartengestaltung, Textilesgestalten, Fasnacht
    .clear

  #cv_doris
    .column.two.reset
      %h5 Privat
    .column.ten.reset
      Geboren am 5. März 1969 in Liestal
      %br/
      Lebt mit ihrer Familie in Basel
    .clear

    %hr.hr_us
    .column.two.reset
      %h5 Berufliches
    .column.ten.reset
      .column.three.reset
        #title_institut Figurentheater
      .column.eight.reset
        Gründet 2003 ihr eigenes
        %a{href: "http://www.figurentheater-weiller.ch"}Figurentheater.
        %br/
        Verschiedene Stücke für Kinder und Erwachsene im Repertoire. Auftritte in Kleintheater, Gemeinden und Schulen.

      .clear
      %br/
      .column.three.reset
        #title_institut Sozialpädagogin
      .column.eight.reset
        Führt Projekte  in Schulen im Kanton Baselstadt zum Thema „Figuren bauen & spielen „ durch. ( Mus-e )
        %br/
        Arbeitet als Sozialpädagogin teilzeit in einem Wohnheim in Basel. 
      .clear
      %br/
      .column.three.reset
        #title_institut Umweltpädagogik
      .column.eight.reset
        Seit 2016 als Mme Poubelle als Umwelt – und Abfallpädagogin in Gemeinden in Kanton Baselland unterwegs.
      .clear
    .clear
    %hr.hr_us
    .column.two.reset
      %h5 Berufliche Entwicklung
    .column.ten.reset
      #timeline.container
        .timeline-block
          .timeline-content
            %h2 Nachdiplomstudium Figurentheater Hochschule Zürich
            %p Zürich
            %span.date 2001-2004
        .timeline-block
          .timeline-content
            %h2 Einstieg beim Figurentheater Felucca
            %span.date 1994-2002
        .timeline-block
          .timeline-content
            %h2 Ausbildung als Sozialpädagogin
            %span.date 1993-1996
        .timeline-block
          .timeline-content
            %h2 Lehre als Holzbildhauerin
            %span.date 1987-1991
        .timeline-block
          .timeline-content
            %h2 Kunstgewerbschule in Basel
            %p Basel
            %span.date 1986-1987
    .clear
    %hr.hr_us
    .column.two.reset
      %h5 Weitere Interessen
    .column.ten.reset
      Theaterbesuche, lesen, mit meiner Familie verschiedene Aktivitäten erleben, gärtnern, wandern, schwimmen usw.
    .clear

  #cv_david
    .column.two.reset
      %h5 Privat
    .column.ten.reset
      Geboren am 23. Januar 1986 in Baar
      %br/
      Vater von Zwillingstöchtern (Geboren 2010)
    .clear

    %hr.hr_us
    .column.two.reset
      %h5 Berufliches
    .column.ten.reset
      .column.three.reset
        #title_institut Pädagogik
      .column.eight.reset
        Seit 2016 arbeit als Lehrer und Betreuer in der Sonderschule Lernzeit GmbH in Zollbrück
        %br/
        Seit 2015 verschiedene Praktika an Rudolf Steiner Schulen im Rahmen der berufsbegleitenden Ausbildung zum Klassen- und Gartenbaulehrer

      .clear
      %br/
      .column.three.reset
        #title_institut Musik
      .column.eight.reset
        Kursleiter von Didgeridoo-Kursen
        %br/
        Konzerte mit World- und Folk Music Ensembles
      .clear
    .clear
    %hr.hr_us
    .column.two.reset
      %h5 Berufliche Entwicklung
    .column.ten.reset
      #timeline.container
        .timeline-block
          .timeline-content
            %h2 Studium an der Akademie für anthroposo-phische Pädagogik (AfaP)
            %p Dornach
            %span.date 2014-2018
        .timeline-block
          .timeline-content
            %h2 Begleitung und Betreuung von Menschen mit geistigen Behinderungen
            %P verschiedene Institutionen
            %span.date 2008–2017
        .timeline-block
          .timeline-content
            %h2 Praktikum, Sprachaufenthalte und Reisen
            %p England und Südamerika
            %span.date 2005–2008
        .timeline-block
          .timeline-content
            %h2 Lehre als Kaufmännischer Angestellter 
            %p Schweiz. Vereinigung für Qualitäts- und Managementsysteme
            %span.date 2002–2005
    .clear
    %hr.hr_us
    .column.two.reset
      %h5 Weitere Interessen
    .column.ten.reset
      Gärtnern und das damit verbundene Kochen und Weiterverarbeiten der Gartenerzeugnisse, Musik, Improvisation, Spiel, Bewegungs- und Kampfkünste.
    .clear


  #cv_sabine
    .column.two.reset
      %h5 Privat
    .column.ten.reset
      Geboren am 22. Januar 1980
      %br/
      Lebt in Bottmingen
    .clear

    %hr.hr_us
    .column.two.reset
      %h5 Berufliches
    .column.ten.reset
      .column.three.reset
        #title_institut Theater
      .column.eight.reset
        Seit 2005 in diversen Engagements als Musicaldarstellerin und Schauspielerin 
        %br/
        Seit 2013 als ForumSchauspierin bei der Medien- und TheaterFalle bzw. beim Verein Reactor tätig
        %br/
        2014 und 2017 Produktion eigener Theaterstücke mit Theater vor dem Mond
        %br/
        Seit 2014 diverse Auftritte mit „The Urban Country Club“, Country Duo
      .clear
      %br/
      .column.three.reset
        #title_institut Sprecherin
      .column.eight.reset
        Seit 2015 als Sprecherin in Hörspielen und Werbung
      .clear
    .clear
    %hr.hr_us
    .column.two.reset
      %h5 Berufliche Entwicklung
    .column.ten.reset
      #timeline.container
        .timeline-block
          .timeline-content
            %h2 Weiterbildung in Theaterpädagogik
            %span.date 2019
        .timeline-block
          .timeline-content
            %h2 Clown Weiterbildung bei Yve Stöcklin
            %P Basel
            %span.date 2011
        .timeline-block
          .timeline-content
            %h2 Schauspielstudium an der Hochschule für Musik und Theater
            %p Rostock
            %span.date 2005–2007
        .timeline-block
          .timeline-content
            %h2 Musicalausbildung an der Universität für Musik und darstellende Kunst
            %p Wien
            %span.date 2001–2004
    .clear
    %hr.hr_us
    .column.two.reset
      %h5 Weitere Interessen
    .column.ten.reset
      Die Arbeit in meinem wunderbaren kleinen Garten, Wandern, Tanzen
    .clear



  #cv_michelle
    .column.two.reset
      %h5 Privat
    .column.ten.reset
      Geboren am 20. Februar 1985
      %br/
      Lebt in Basel
    .clear

    %hr.hr_us
    .column.two.reset
      %h5 Berufliches
    .column.ten.reset
      .column.three.reset
        #title_institut Pädagogik
      .column.eight.reset
        Seit 2010 angestellt als Klassenlehrperson 3.-6. Schuljahr an der Primarschule Therwil
        %br/
        Seit 2013 Mitverantwortliche für die Einführung des Lehrplans 21 (Lokale Sachverständige) an der Primarschule Therwil
        %br/
        %br/
        Von 2008 - 2010 angestellt als Primarschullehrperson in einer 4.Klasse/5. Klasse in Erlinsbach (SO)
      .clear
    .clear
    %hr.hr_us
    .column.two.reset
      %h5 Berufliche Entwicklung
    .column.ten.reset
      #timeline.container
        .timeline-block
          .timeline-content
            %h2 CAS in Naturbezogener Umweltbildung
            %P Zürcher Fachhochschule für angewandte Wissenschaften
            %span.date 2012-2015
        .timeline-block
          .timeline-content
            %h2 Bachelor of Arts in Primary Education (Primarstufe)
            %p Pädagogische Hochschule Liestal
            %span.date 2007–2011
        .timeline-block
          .timeline-content
            %h2 Certificate of Advanced Studies in Naturbezogener Umweltbildung
            %p Zürcher Fachhochschule für angewandte Wissenschaften
            %span.date 2004–2007
    .clear
    %hr.hr_us
    .column.two.reset
      %h5 Weitere Interessen
    .column.ten.reset
      Konzeptionelle Mitgestaltung im Vorstand der Nuglar Gärten, Aufbauarbeit einer solidarischen Landwirtschaft in Nuglar-St. Pantaleon. 
      %br/
      Damit verbunden das Haltbarmachen und Weiterverarbeiten der bio-dynamischen Lebensmittel.
      %br/
      Seit vielen Jahren spiele ich Querflöte. Bin gerne in Bewegung, bei täglichen Velofahrten und aktiv im polysportiven Erwachsenensport.
    .clear

app/views/static_pages/home.html.haml
%article#main
	%h1 Umwelt- und Abfallpädagogik-Kurse
	%p
		In der ganzen Schweiz vergrössert sich jährlich die Abfallmenge pro Person, Littering ist längst nicht nur ein Problem an neuralgischen Orten in Städten und Agglomerationen. Die Themenbereiche wie Ressourcenschonung, erneuerbare Energien sind in einem stetigen Wandel und sehr vielseitig.
		%br/
		Viele Gemeinden und Städte in der Schweiz haben sich deshalb schon seit langem entschieden, den Lehrpersonen für die Vermittlung dieser wichtigen und vielschichtigen Themen Umwelt- und AbfallpädagogInnen zur Unterstützung anzubieten und zu finanzieren.
	%br/
	%p
		Wir, Barbara Schumacher und Birgit Gluth, bieten seit vielen Jahren ein abwechslungsreiches und umfassendes Umwelt- und Abfallpädagogik-Kursprogramm vom Kindergarten über die Primar- und Sekundarschule bis hin zur Erwachsenenbildung an.
	%br/
	%p
		Die Themen Abfallvermeidung, Recycling und Littering sowie Energieeffizienz und erneuerbare Energien werden stufengerecht und spannend vermittelt. Wir passen die Kursthemen der jeweiligen Stufe, dem Lehrplan und den Abfall- und Umweltsituationen in der Schule und der Gemeinde wie aber auch den Wünschen der Lehrpersonen und Gemeindeverantwortlichen an. Den Lehrpersonen ist es auch möglich, nach Rücksprache mit der Kursleiterin, die Schwerpunkte der Kurse zu wählen.

app/views/static_pages/kurs_effizienz.html.haml
%article#main
  %h1 
    %li= link_to "Tolles Fest zum Schulschluss 2014 (BiBo)", "http://www.bibo.ch/pdf/2014_28_10_07_2014_ob.pdf"

app/views/static_pages/medienberichte.html.haml
%article#main

	%h4 Oktober 2016
	%ul
		%li
			=link_to "Natur und Erlebnispfad in Therwil", "http://video.fadeout.ch/de/therwilaktuell/therwil/#topic_6"
	%br/

	%h4 September 2015
	%ul
		%li
			=link_to "Littering- und Abfall-Projektwoche im Meiriacker (Seite 2)", "http://www.binningeranzeiger.ch/images/stories/PDF/35-2015-w.pdf"
	%br/

	%h4 August 2015
	%ul
		%li
			=link_to "Umweltpädagogin: «Littering ist eine Art Gesellschaftskritik»", "http://www.tageswoche.ch/de/2015_33/basel/695616/%C2%ABM%C3%BCll-ist-etwas-Intimes%C2%BB.htm"
	%br/

	%h4 Juni 2015
	%ul
		%li
			Einsatz für die Umwelt
		.column.half
			%a.fancybox{href: image_path('media/Einsatz_fuer_die_Umwelt.jpg'), rel: "gallery", title: "Einsatz für die Umwelt"}
				= image_tag('media/Einsatz_fuer_die_Umwelt.jpg' )
	%br/

	%h4 März 2015
	%ul
		%li
			=link_to "Hier lernen Kinder etwas über Abfall - das hat bereits konkrete Folgen (BZ)", "http://www.bzbasel.ch/basel/baselbiet/hier-lernen-kinder-etwas-ueber-abfall-das-hat-bereits-konkrete-folgen-128832413"
	%br/

	%h4 Juli 2014
	%ul
		%li
			Wenn aus Schülern Forscher werden
		.column.half
			%a.fancybox{href: image_path('media/Kompostmobil_Allschwil.jpg'), rel: "gallery", title: "Kompostmobil in Allschwil"}
				= image_tag('media/Kompostmobil_Allschwil.jpg' )

		%li
			=link_to "Tolles Fest zum Schulschluss(BiBo)", "http://www.bibo.ch/pdf/2014_28_10_07_2014_ob.pdf"
	%br/

/	 %h3 Oberwil Kindergarten Sägestrasse Hochbeet einrichten
/	 .column.half
/		= link_to "Artikel", 'data/Bibo_Hochbeet.pdf'

	

app/views/static_pages/offers.html.haml
%article#main
	- if flash[:notice]
		.notice= flash[:notice]
	%p.register_course.keep-right
		= link_to "Für Kurs anmelden", new_contact_path()
	#accordion
		%h4
			%a{href: "#"} Primarschule und Kindergarten
		= render 'primarKindergarten'

		%h4
			%a{href: "#"} Sekundarschule
		= render 'sekundar'

		%h4
			%a{href: "#"} Lehrerweiterbildung
		= render 'lehrer_weiterbildung'

		%h4
			%a{href: "#"} Erwachsenbildung
		= render 'eltern'